name: NodeJS CD with Dockhub

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4 #prebuild action (file js ,docker file)

      - name: Login to Dockhub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_TOKEN}} 

      - name: Build and push # docker file build to image into docker hub
        uses: docker/build-push-action@v5
        with:
          context: . # call docker file
          push : true  # accept push iamge into dockerhub
          tags: ${{secrets.DOCKER_USERNAME}}/eshopweb:latest #create tag into repo
        
 


